being naughty

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -146,129 +146,129 @@ jobs:
           BUCKET_NAME: namada-wasm-master
           AWS_REGION: eu-west-1
 
-  unit-and-integration-tests:
-    runs-on: 
-      group: gians-runners
-    timeout-minutes: 80
-    needs: [build-wasm]
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [ubuntu-20.04]
-        nightly_version: [nightly-2023-06-01]
-        mold_version: [1.11.0]
-        make:
-          - name: ABCI
-            suffix: ''
-            cache_key: namada
-            cache_version: v2
-            tendermint_artifact: tendermint-unreleased-v0.1.4-abciplus
+  # unit-and-integration-tests:
+  #   runs-on: 
+  #     group: gians-runners
+  #   timeout-minutes: 80
+  #   needs: [build-wasm]
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       os: [ubuntu-20.04]
+  #       nightly_version: [nightly-2023-06-01]
+  #       mold_version: [1.11.0]
+  #       make:
+  #         - name: ABCI
+  #           suffix: ''
+  #           cache_key: namada
+  #           cache_version: v2
+  #           tendermint_artifact: tendermint-unreleased-v0.1.4-abciplus
 
-    env:
-      CARGO_INCREMENTAL: 0
-      RUST_BACKTRACE: full
-      RUSTC_WRAPPER: sccache
-      SCCACHE_CACHE_SIZE: 100G
-      SCCACHE_BUCKET: namada-sccache-master
+  #   env:
+  #     CARGO_INCREMENTAL: 0
+  #     RUST_BACKTRACE: full
+  #     RUSTC_WRAPPER: sccache
+  #     SCCACHE_CACHE_SIZE: 100G
+  #     SCCACHE_BUCKET: namada-sccache-master
 
-    steps:
-      - name: Checkout repo
-        uses: actions/checkout@v3
-        if: ${{ github.event_name != 'pull_request_target' }}
-      - name: Checkout PR
-        uses: actions/checkout@v3
-        if: ${{ github.event_name == 'pull_request_target' }}
-        # See comment in build-and-test.yml
-        with:
-          ref: ${{ github.event.pull_request.head.sha }}
-      - name: Remove some unused data in github runners
-        run: |
-          sudo rm -rf /usr/share/dotnet
-          sudo rm -rf /opt/ghc
-          sudo rm -rf "/usr/local/share/boost"
-          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
-      - name: Configure AWS Credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        with:
-          role-to-assume: arn:aws:iam::375643557360:role/anoma-github-action-ci-master
-          aws-region: eu-west-1
-      - name: Install Protoc
-        uses: arduino/setup-protoc@v1
-        with:
-          repo-token: ${{ secrets.GITHUB_TOKEN }}
-      - name: Install sccache (ubuntu-20.04)
-        if: matrix.os == 'ubuntu-20.04'
-        env:
-          LINK: https://github.com/mozilla/sccache/releases/download
-          SCCACHE_VERSION: v0.3.0
-        run: |
-          SCCACHE_FILE=sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl
-          mkdir -p $HOME/.local/bin
-          curl -L "$LINK/$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz" | tar xz
-          mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
-          chmod +x $HOME/.local/bin/sccache
-          echo "$HOME/.local/bin" >> $GITHUB_PATH
-      - name: Install sccache (macos-latest)
-        if: matrix.os == 'macos-latest'
-        run: |
-          brew update
-          brew install sccache
-      - name: Setup rust toolchain
-        uses: oxidecomputer/actions-rs_toolchain@ad3f86084a8a5acf2c09cb691421b31cf8af7a36
-        with:
-          profile: default
-          override: true
-      - name: Setup rust nightly
-        uses: oxidecomputer/actions-rs_toolchain@ad3f86084a8a5acf2c09cb691421b31cf8af7a36
-        with:
-          toolchain: ${{ matrix.nightly_version }}
-          profile: default
-      - name: Cache cargo registry
-        uses: actions/cache@v3
-        continue-on-error: false
-        with:
-          path: |
-            ~/.cargo/registry
-            ~/.cargo/git
-          key: ${{ runner.os }}-${{ matrix.make.cache_key }}-${{ matrix.make.cache_version }}-cargo-${{ hashFiles('**/Cargo.lock') }}
-          restore-keys: ${{ runner.os }}-${{ matrix.make.cache_key }}-${{ matrix.make.cache_version }}-cargo-
-      - name: Start sccache server
-        run: sccache --start-server
-      - name: Install mold linker
-        run: |
-          wget -q -O- https://github.com/rui314/mold/releases/download/v${{ matrix.mold_version }}/mold-${{ matrix.mold_version }}-x86_64-linux.tar.gz | tar -xz
-          mv mold-${{ matrix.mold_version }}-x86_64-linux/bin/mold  /usr/local/bin
-      - name: Download MASP parameters
-        run: |
-          mkdir -p /home/runner/.masp-params
-          curl -o /home/runner/.masp-params/masp-spend.params -L https://github.com/anoma/masp-mpc/releases/download/namada-trusted-setup/masp-spend.params\?raw\=true
-          curl -o /home/runner/.masp-params/masp-output.params -L https://github.com/anoma/masp-mpc/releases/download/namada-trusted-setup/masp-output.params?raw=true
-          curl -o /home/runner/.masp-params/masp-convert.params -L https://github.com/anoma/masp-mpc/releases/download/namada-trusted-setup/masp-convert.params?raw=true
-      - name: Download wasm artifacts
-        uses: actions/download-artifact@v3
-        with:
-          name: wasm-${{ github.event.pull_request.head.sha|| github.sha }}
-          path: ./wasm
-      - uses: taiki-e/install-action@cargo-llvm-cov
-      - name: Check crates build with default features
-        run: make check-crates
-      - name: Run unit and integration tests
-        run: make test-coverage${{ matrix.make.suffix }}
-        env:
-          NAMADA_MASP_PARAMS_DIR: /home/runner/.masp-params
-          RUSTFLAGS: "-C linker=clang -C link-arg=-fuse-ld=/usr/local/bin/mold"
-      - name: Upload coverage
-        uses: actions/upload-artifact@v3
-        with:
-          name: coverage${{ matrix.make.suffix }}-${{ github.event.pull_request.head.sha || github.sha }}
-          path: target/html
-          retention-days: 3
-      - name: Print sccache stats
-        if: always()
-        run: sccache --show-stats
-      - name: Stop sccache server
-        if: always()
-        run: sccache --stop-server || true
+  #   steps:
+  #     - name: Checkout repo
+  #       uses: actions/checkout@v3
+  #       if: ${{ github.event_name != 'pull_request_target' }}
+  #     - name: Checkout PR
+  #       uses: actions/checkout@v3
+  #       if: ${{ github.event_name == 'pull_request_target' }}
+  #       # See comment in build-and-test.yml
+  #       with:
+  #         ref: ${{ github.event.pull_request.head.sha }}
+  #     - name: Remove some unused data in github runners
+  #       run: |
+  #         sudo rm -rf /usr/share/dotnet
+  #         sudo rm -rf /opt/ghc
+  #         sudo rm -rf "/usr/local/share/boost"
+  #         sudo rm -rf "$AGENT_TOOLSDIRECTORY"
+  #     - name: Configure AWS Credentials
+  #       uses: aws-actions/configure-aws-credentials@v1
+  #       with:
+  #         role-to-assume: arn:aws:iam::375643557360:role/anoma-github-action-ci-master
+  #         aws-region: eu-west-1
+  #     - name: Install Protoc
+  #       uses: arduino/setup-protoc@v1
+  #       with:
+  #         repo-token: ${{ secrets.GITHUB_TOKEN }}
+  #     - name: Install sccache (ubuntu-20.04)
+  #       if: matrix.os == 'ubuntu-20.04'
+  #       env:
+  #         LINK: https://github.com/mozilla/sccache/releases/download
+  #         SCCACHE_VERSION: v0.3.0
+  #       run: |
+  #         SCCACHE_FILE=sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl
+  #         mkdir -p $HOME/.local/bin
+  #         curl -L "$LINK/$SCCACHE_VERSION/$SCCACHE_FILE.tar.gz" | tar xz
+  #         mv -f $SCCACHE_FILE/sccache $HOME/.local/bin/sccache
+  #         chmod +x $HOME/.local/bin/sccache
+  #         echo "$HOME/.local/bin" >> $GITHUB_PATH
+  #     - name: Install sccache (macos-latest)
+  #       if: matrix.os == 'macos-latest'
+  #       run: |
+  #         brew update
+  #         brew install sccache
+  #     - name: Setup rust toolchain
+  #       uses: oxidecomputer/actions-rs_toolchain@ad3f86084a8a5acf2c09cb691421b31cf8af7a36
+  #       with:
+  #         profile: default
+  #         override: true
+  #     - name: Setup rust nightly
+  #       uses: oxidecomputer/actions-rs_toolchain@ad3f86084a8a5acf2c09cb691421b31cf8af7a36
+  #       with:
+  #         toolchain: ${{ matrix.nightly_version }}
+  #         profile: default
+  #     - name: Cache cargo registry
+  #       uses: actions/cache@v3
+  #       continue-on-error: false
+  #       with:
+  #         path: |
+  #           ~/.cargo/registry
+  #           ~/.cargo/git
+  #         key: ${{ runner.os }}-${{ matrix.make.cache_key }}-${{ matrix.make.cache_version }}-cargo-${{ hashFiles('**/Cargo.lock') }}
+  #         restore-keys: ${{ runner.os }}-${{ matrix.make.cache_key }}-${{ matrix.make.cache_version }}-cargo-
+  #     - name: Start sccache server
+  #       run: sccache --start-server
+  #     - name: Install mold linker
+  #       run: |
+  #         wget -q -O- https://github.com/rui314/mold/releases/download/v${{ matrix.mold_version }}/mold-${{ matrix.mold_version }}-x86_64-linux.tar.gz | tar -xz
+  #         mv mold-${{ matrix.mold_version }}-x86_64-linux/bin/mold  /usr/local/bin
+  #     - name: Download MASP parameters
+  #       run: |
+  #         mkdir -p /home/runner/.masp-params
+  #         curl -o /home/runner/.masp-params/masp-spend.params -L https://github.com/anoma/masp-mpc/releases/download/namada-trusted-setup/masp-spend.params\?raw\=true
+  #         curl -o /home/runner/.masp-params/masp-output.params -L https://github.com/anoma/masp-mpc/releases/download/namada-trusted-setup/masp-output.params?raw=true
+  #         curl -o /home/runner/.masp-params/masp-convert.params -L https://github.com/anoma/masp-mpc/releases/download/namada-trusted-setup/masp-convert.params?raw=true
+  #     - name: Download wasm artifacts
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: wasm-${{ github.event.pull_request.head.sha|| github.sha }}
+  #         path: ./wasm
+  #     - uses: taiki-e/install-action@cargo-llvm-cov
+  #     - name: Check crates build with default features
+  #       run: make check-crates
+  #     - name: Run unit and integration tests
+  #       run: make test-coverage${{ matrix.make.suffix }}
+  #       env:
+  #         NAMADA_MASP_PARAMS_DIR: /home/runner/.masp-params
+  #         RUSTFLAGS: "-C linker=clang -C link-arg=-fuse-ld=/usr/local/bin/mold"
+  #     - name: Upload coverage
+  #       uses: actions/upload-artifact@v3
+  #       with:
+  #         name: coverage${{ matrix.make.suffix }}-${{ github.event.pull_request.head.sha || github.sha }}
+  #         path: target/html
+  #         retention-days: 3
+  #     - name: Print sccache stats
+  #       if: always()
+  #       run: sccache --show-stats
+  #     - name: Stop sccache server
+  #       if: always()
+  #       run: sccache --stop-server || true
 
   namada-release:
     runs-on: 
